import { Category, LiveChannel, MovieItem, SeriesItem } from '../types/iptv';

export const DEMO_LIVE_CATEGORIES: Category[] = [
  { id: 'cat_news', name: 'Notícias & Documentários', type: 'live' },
  { id: 'cat_sports', name: 'Esportes & Ação', type: 'live' },
  { id: 'cat_entertainment', name: 'Entretenimento & Música', type: 'live' },
  { id: 'cat_tech', name: 'Tecnologia & Ciência', type: 'live' },
];

export const DEMO_LIVE_CHANNELS: LiveChannel[] = [
  {
    id: 'demo_live_1',
    name: 'NASA TV HD Live',
    category: 'Tecnologia & Ciência',
    categoryId: 'cat_tech',
    streamUrl: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg',
    currentProgram: 'ISS Live Views & Earth from Orbit',
  },
  {
    id: 'demo_live_2',
    name: 'Red Bull TV Action Sports',
    category: 'Esportes & Ação',
    categoryId: 'cat_sports',
    streamUrl: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
    logo: 'https://images.redbull.com/image/upload/w_200,h_200,c_fill,g_auto/q_auto,f_auto/redbullcom/2020/6/15/d5sqb4k64c8s9kff9r7d/red-bull-tv-logo',
    currentProgram: 'Extreme Sports World Tour',
  },
  {
    id: 'demo_live_3',
    name: 'DW News English',
    category: 'Notícias & Documentários',
    categoryId: 'cat_news',
    streamUrl: 'https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/75/Deutsche_Welle_symbol_2012.svg',
    currentProgram: 'Global News Hourly Update',
  },
  {
    id: 'demo_live_4',
    name: 'Al Jazeera English HD',
    category: 'Notícias & Documentários',
    categoryId: 'cat_news',
    streamUrl: 'https://live-hls-web-aje.getaj.net/AJE/03.m3u8',
    logo: 'https://upload.wikimedia.org/wikipedia/en/f/f2/Aljazeera_eng.svg',
    currentProgram: 'Live International Coverage',
  },
  {
    id: 'demo_live_5',
    name: 'Sintel TV Live Showcase',
    category: 'Entretenimento & Música',
    categoryId: 'cat_entertainment',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logo: 'https://images.unsplash.com/photo-1578022761797-b8636ac1773c?w=200&auto=format&fit=crop&q=60',
    currentProgram: 'Open Source Cinema Marathon',
  },
];

export const DEMO_MOVIE_CATEGORIES: Category[] = [
  { id: 'cat_m_action', name: 'Ação & Ficção Científica', type: 'movie' },
  { id: 'cat_m_animation', name: 'Animação & Família', type: 'movie' },
  { id: 'cat_m_drama', name: 'Drama & Clássicos', type: 'movie' },
];

export const DEMO_MOVIES: MovieItem[] = [
  {
    id: 'demo_mov_1',
    name: 'Big Buck Bunny (4K Remaster)',
    title: 'Big Buck Bunny (4K Remaster)',
    category: 'Animação & Família',
    categoryId: 'cat_m_animation',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    poster: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Big_buck_bunny_poster_big.jpg',
    backdrop: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
    rating: 4.8,
    year: '2008',
    duration: '9m 56s',
    genre: 'Animação, Comédia',
    plot: 'Um grande e gentil coelho acorda em uma bela manhã de primavera, apenas para ter seu sossego perturbado por três roedores travessos da floresta.',
    director: 'Sacha Goedegebure',
    cast: 'Jan Morgenstern, Ton Roosendaal',
  },
  {
    id: 'demo_mov_2',
    name: 'Tears of Steel (Sci-Fi VFX)',
    title: 'Tears of Steel (Sci-Fi VFX)',
    category: 'Ação & Ficção Científica',
    categoryId: 'cat_m_action',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    poster: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Tears_of_Steel_poster.jpg/800px-Tears_of_Steel_poster.jpg',
    backdrop: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80',
    rating: 4.5,
    year: '2012',
    duration: '12m 14s',
    genre: 'Ficção Científica, Cyberpunk',
    plot: 'Em um futuro distópico em Amsterdã, um grupo de cientistas e soldados tenta reconstruir um evento do passado para salvar a humanidade de robôs destruidores.',
    director: 'Ian Hubert',
    cast: 'Derek de Lint, Sergio Hasselbaink, Rogier Schippers',
  },
  {
    id: 'demo_mov_3',
    name: 'Sintel - A Jornada',
    title: 'Sintel - A Jornada',
    category: 'Animação & Família',
    categoryId: 'cat_m_animation',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    poster: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Sintel_poster.jpg',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    rating: 4.9,
    year: '2010',
    duration: '14m 48s',
    genre: 'Animação, Fantasia, Aventura',
    plot: 'Uma jovem solitária resgata um pequeno dragão ferido e forma um vínculo inquebrável, embarcando em uma perigosa jornada através de terras inóspitas quando ele é capturado.',
    director: 'Colin Levy',
    cast: 'Halina Reijn, Thom Hoffman',
  },
  {
    id: 'demo_mov_4',
    name: 'Elephants Dream',
    title: 'Elephants Dream',
    category: 'Ação & Ficção Científica',
    categoryId: 'cat_m_action',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    poster: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Elephants_Dream_poster.png/800px-Elephants_Dream_poster.png',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80',
    rating: 4.2,
    year: '2006',
    duration: '10m 54s',
    genre: 'Ficção Científica, Surrealismo',
    plot: 'Dois personagens exploram uma complexa máquina infinita gerada pelas suas próprias memórias e conflitos de realidade.',
    director: 'Bassam Kurdali',
    cast: 'Tygo Gernandt, Cas Jansen',
  },
];

export const DEMO_SERIES_CATEGORIES: Category[] = [
  { id: 'cat_s_tech', name: 'Documentários & Tech', type: 'series' },
  { id: 'cat_s_nature', name: 'Natureza & Aventura', type: 'series' },
];

export const DEMO_SERIES: SeriesItem[] = [
  {
    id: 'demo_ser_1',
    name: 'Cosmos & Universo em 4K',
    title: 'Cosmos & Universo em 4K',
    category: 'Documentários & Tech',
    categoryId: 'cat_s_tech',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1200&auto=format&fit=crop&q=80',
    rating: 4.9,
    year: '2023',
    genre: 'Ciência, Espaço, Documentário',
    plot: 'Uma expedição fascinante pelos segredos do cosmos, nebulosas distantes e as últimas descobertas astronômicas.',
    seasons: [
      {
        seasonNumber: 1,
        name: 'Temporada 1: O Sistema Solar',
        episodes: [
          {
            id: 'demo_ep_1_1',
            seasonNum: 1,
            episodeNum: 1,
            title: 'Episódio 1: Além da Atmosfera',
            streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            thumbnail: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=500&auto=format&fit=crop&q=60',
            plot: 'A exploração dos limites da órbita terrestre e as estações espaciais.',
            duration: '15m',
          },
          {
            id: 'demo_ep_1_2',
            seasonNum: 1,
            episodeNum: 2,
            title: 'Episódio 2: Gigantes Gasosos',
            streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
            thumbnail: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=500&auto=format&fit=crop&q=60',
            plot: 'Mergulho nas tempestades de Júpiter e nos misteriosos anéis de Saturno.',
            duration: '14m',
          },
        ],
      },
      {
        seasonNumber: 2,
        name: 'Temporada 2: Galáxias Distantes',
        episodes: [
          {
            id: 'demo_ep_2_1',
            seasonNum: 2,
            episodeNum: 1,
            title: 'Episódio 1: Buracos Negros e Matéria Escura',
            streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
            thumbnail: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=500&auto=format&fit=crop&q=60',
            plot: 'Investigando os limites da física moderna no horizonte de eventos.',
            duration: '18m',
          },
        ],
      },
    ],
  },
  {
    id: 'demo_ser_2',
    name: 'Planeta Selvagem: Horizontes',
    title: 'Planeta Selvagem: Horizontes',
    category: 'Natureza & Aventura',
    categoryId: 'cat_s_nature',
    poster: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=80',
    rating: 4.7,
    year: '2022',
    genre: 'Natureza, Vida Selvagem',
    plot: 'Acompanhe as maiores migrações do planeta e a vida selvagem nos ecossistemas mais extremos da Terra.',
    seasons: [
      {
        seasonNumber: 1,
        name: 'Temporada 1: Savana & Oceanos',
        episodes: [
          {
            id: 'demo_ep_s2_1',
            seasonNum: 1,
            episodeNum: 1,
            title: 'Episódio 1: O Reino dos Predadores',
            streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
            thumbnail: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=500&auto=format&fit=crop&q=60',
            plot: 'Estratégias de sobrevivência no coração do Serengeti.',
            duration: '12m',
          },
          {
            id: 'demo_ep_s2_2',
            seasonNum: 1,
            episodeNum: 2,
            title: 'Episódio 2: As Profundezas Azuis',
            streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
            thumbnail: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=500&auto=format&fit=crop&q=60',
            plot: 'A vida nos recifes de corais e abismos marinhos inexplorados.',
            duration: '16m',
          },
        ],
      },
    ],
  },
];
